---
twitter:
    consumer_key: API_KEY
    consumer_secret: API_SECRET
    access_token: ACCESS_TOKEN
    access_token_secret: ACCESS_TOKEN_SECRET

adaptors:
    file: MarkovBot\Adaptor\FileAdaptor

markov.settings:
    method: mixedsource
    sources:
        - file://data/nietzsche.txt
        - file://data/mobydick.txt
    chain: 2
    blocks: 10
    themes:
        - love
